# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0  # Long Term Support
  - 1    # Current Stable
matrix:
  allow_failures:
    - julia: nightly
branches:
  only:
    - master
    - /release-.*/
notifications:
  email: false
